import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import type { Pathway, Molecule } from "@/types/pathway";
import type { Enzyme } from "@/types/enzyme";
import { FlaskConical, CheckCircle2, Loader2 } from "lucide-react";

// ── Selectable molecules ────────────────────────────────────────────────────

const START_MOLECULES: Molecule[] = [
  {
    name: "L-Tyrosine",
    smiles: "N[C@@H](Cc1ccc(O)cc1)C(O)=O",
    formula: "C₉H₁₁NO₃",
  },
  {
    name: "D-Glucose",
    smiles: "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O",
    formula: "C₆H₁₂O₆",
  },
  {
    name: "Chorismate",
    smiles: "OC(=O)C=C[C@@H]1OC(CC1=O)C=CC(O)=O",
    formula: "C₁₀H₁₀O₆",
  },
];

const END_MOLECULES: Molecule[] = [
  {
    name: "L-DOPA",
    smiles: "N[C@@H](Cc1ccc(O)c(O)c1)C(O)=O",
    formula: "C₉H₁₁NO₄",
  },
  {
    name: "Pyruvate",
    smiles: "CC(=O)C(O)=O",
    formula: "C₃H₄O₃",
  },
  {
    name: "Prephenate",
    smiles: "OC(=O)C(=O)C[C@]1(O)CC=CC(=O)C1",
    formula: "C₁₀H₁₀O₆",
  },
];

// ── Reaction type per pair ──────────────────────────────────────────────────

const REACTION_TYPES: Record<string, string> = {
  "L-Tyrosine|L-DOPA":       "Aromatic hydroxylation",
  "L-Tyrosine|Pyruvate":     "Deamination / decarboxylation",
  "L-Tyrosine|Prephenate":   "Retroaldol rearrangement",
  "D-Glucose|L-DOPA":        "Oxidative aromatic synthesis",
  "D-Glucose|Pyruvate":      "Phosphorylation / glycolysis",
  "D-Glucose|Prephenate":    "Shikimate pathway branch",
  "Chorismate|L-DOPA":       "Transamination / hydroxylation",
  "Chorismate|Pyruvate":     "Pyruvate elimination",
  "Chorismate|Prephenate":   "Claisen rearrangement",
};

const ENZYME_NAME_TEMPLATES: Record<string, string[]> = {
  "Aromatic hydroxylation":          ["Tyrosine Hydroxylase", "Phenylalanine 4-Hydroxylase", "Pterin-dependent Hydroxylase"],
  "Deamination / decarboxylation":   ["Tyrosine Decarboxylase", "Aromatic-L-amino-acid Decarboxylase", "Tyrosine Ammonia-lyase"],
  "Retroaldol rearrangement":        ["Tyrosine Mutase", "Aromatase (TyrM)", "Retroaldolase (RalB)"],
  "Oxidative aromatic synthesis":    ["Glucose Oxidase", "FAD-dependent Oxygenase", "Laccase-like Oxidase"],
  "Phosphorylation / glycolysis":    ["Hexokinase", "Glucokinase", "ATP-dependent Glucokinase"],
  "Shikimate pathway branch":        ["DAHP Synthase", "Shikimate Kinase", "EPSP Synthase"],
  "Transamination / hydroxylation":  ["Anthranilate Synthase", "Amino Transferase (PyrA)", "Hydroxylase (ChlH)"],
  "Pyruvate elimination":            ["Chorismate Pyruvate-lyase", "Isochorismate Synthase", "Pyruvate Lyase"],
  "Claisen rearrangement":           ["Chorismate Mutase", "Claisen Rearrangase (PheA)", "Chorismate Mutase (TyrA domain)"],
};

const VENDORS   = ["Sigma-Aldrich", "Enzyme Works", "Prozomix", "Creative Enzymes", "BioVendor"];
const ORGANISMS = ["E. coli K-12", "B. subtilis", "S. cerevisiae", "P. putida", "T. thermophilus"];
const EC_POOLS  = ["1.14.16.2", "4.1.1.28", "5.4.99.5", "2.7.1.1", "4.2.1.20", "2.5.1.54", "1.1.1.25", "4.1.3.27"];

function rnd(min: number, max: number) { return min + Math.random() * (max - min); }
function pick<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]; }

function generateEnzymes(reactionType: string): Enzyme[] {
  const names = ENZYME_NAME_TEMPLATES[reactionType] ?? ["Oxidoreductase", "Transferase", "Lyase"];
  return names.map((name, i) => ({
    id: `gen-${i}`,
    name,
    ecNumber: `EC ${pick(EC_POOLS)}`,
    score: parseFloat(rnd(0.62, 0.97).toFixed(2)),
    organism: pick(ORGANISMS),
    description: `Catalyzes the ${reactionType.toLowerCase()} reaction with high substrate specificity. Characterized from recombinant expression in ${pick(ORGANISMS)}.`,
    optimalPh: `${rnd(6.4, 8.2).toFixed(1)}`,
    optimalTemp: `${Math.round(rnd(28, 55))}°C`,
    kcat: `${Math.round(rnd(5, 90))} s⁻¹`,
    km: `${rnd(0.04, 0.45).toFixed(2)} mM`,
    projectedYield: `${Math.round(rnd(65, 96))}%`,
    vendor: pick(VENDORS),
    vendorLogo: "",
    price: `$${Math.round(rnd(180, 550))}.00 / 1mg`,
    catalogNumber: `GEN-${Math.floor(Math.random() * 9000) + 1000}`,
  }));
}

function generatePathway(name: string, start: Molecule, end: Molecule): Pathway {
  const key = `${start.name}|${end.name}`;
  const reactionType = REACTION_TYPES[key] ?? "Enzymatic transformation";
  return {
    id: "generated",
    name: name.trim() || `${start.name} → ${end.name}`,
    description: `Single-step ${reactionType.toLowerCase()} pathway converting ${start.name} to ${end.name}. Generated by NitroAI analysis.`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: "analyzing",
    steps: [{
      id: "gen-step-1",
      startMolecule: start,
      productMolecule: end,
      reactionType,
      enzymes: generateEnzymes(reactionType),
      hasBruteForce: false,
    }],
  };
}

// ── Loading stages ──────────────────────────────────────────────────────────

const LOADING_STAGES = [
  "Analyzing reaction route...",
  "Searching enzyme databases...",
  "Scoring enzyme candidates...",
  "Building pathway graph...",
  "Finalizing results...",
];

// ── Molecule selector card ──────────────────────────────────────────────────

const MoleculeCard = ({
  molecule, selected, onClick,
}: { molecule: Molecule; selected: boolean; onClick: () => void }) => (
  <button
    type="button"
    onClick={onClick}
    className={cn(
      "w-full text-left rounded-xl border p-3 transition-all",
      selected
        ? "border-primary bg-primary/10 ring-1 ring-primary"
        : "border-border bg-card hover:border-primary/50 hover:bg-accent/50"
    )}
  >
    <div className="flex items-center justify-between">
      <p className="text-sm font-semibold font-mono text-foreground">{molecule.name}</p>
      {selected && <CheckCircle2 className="w-4 h-4 text-primary shrink-0" />}
    </div>
    {molecule.formula && (
      <p className="text-xs font-mono text-muted-foreground mt-0.5">{molecule.formula}</p>
    )}
  </button>
);

// ── Page ────────────────────────────────────────────────────────────────────

export const NewPathwayPage = () => {
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [startMol, setStartMol] = useState<Molecule | null>(null);
  const [endMol, setEndMol]     = useState<Molecule | null>(null);
  const [stage, setStage]       = useState<number>(-1); // -1 = idle

  const isLoading  = stage >= 0;
  const canSubmit  = startMol !== null && endMol !== null && !isLoading;

  useEffect(() => {
    if (stage < 0) return;
    if (stage < LOADING_STAGES.length) {
      const t = setTimeout(() => setStage((s) => s + 1), 620);
      return () => clearTimeout(t);
    }
    // All stages done — navigate with generated pathway in state
    const pathway = generatePathway(name, startMol!, endMol!);
    navigate("/pathways/generated", { state: { pathway } });
  }, [stage]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!canSubmit) return;
    setStage(0);
  };

  const progress = stage >= 0 ? Math.round(((stage) / LOADING_STAGES.length) * 100) : 0;

  return (
    <div className="p-6 h-full overflow-y-auto">
      <div className="max-w-lg mx-auto space-y-6">

        {/* Header */}
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-primary/15 border border-primary/30 flex items-center justify-center shrink-0">
            <FlaskConical className="w-4 h-4 text-primary" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-foreground">New Reaction Pathway</h1>
            <p className="text-sm text-muted-foreground">Select molecules and let NitroAI find the route</p>
          </div>
        </div>

        {/* Loading overlay */}
        {isLoading ? (
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-8 flex flex-col items-center gap-5">
            <div className="w-14 h-14 rounded-full bg-primary/15 border border-primary/30 flex items-center justify-center">
              <Loader2 className="w-7 h-7 text-primary animate-spin" />
            </div>
            <div className="w-full space-y-2 text-center">
              <p className="text-sm font-semibold text-foreground">
                {LOADING_STAGES[Math.min(stage, LOADING_STAGES.length - 1)]}
              </p>
              <div className="w-full bg-muted rounded-full h-1.5">
                <div
                  className="bg-primary h-1.5 rounded-full transition-all duration-500"
                  style={{ width: `${progress}%` }}
                />
              </div>
              <div className="flex justify-between text-[10px] font-mono text-muted-foreground px-0.5">
                {LOADING_STAGES.map((s, i) => (
                  <span key={s} className={cn(i <= stage ? "text-primary" : "")}>
                    {i + 1}
                  </span>
                ))}
              </div>
            </div>
            <p className="text-xs text-muted-foreground font-mono">
              Analyzing {startMol?.name} → {endMol?.name}
            </p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-6">

            {/* Pathway name */}
            <div className="space-y-1.5">
              <Label htmlFor="name">Pathway Name <span className="text-muted-foreground font-normal">(optional)</span></Label>
              <Input
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder={startMol && endMol ? `${startMol.name} → ${endMol.name}` : "e.g. Tyrosine to L-DOPA"}
              />
            </div>

            {/* Starting molecule */}
            <div className="space-y-2">
              <Label>Starting Molecule</Label>
              <div className="grid grid-cols-1 gap-2">
                {START_MOLECULES.map((m) => (
                  <MoleculeCard
                    key={m.name}
                    molecule={m}
                    selected={startMol?.name === m.name}
                    onClick={() => setStartMol(m)}
                  />
                ))}
              </div>
            </div>

            {/* Ending molecule */}
            <div className="space-y-2">
              <Label>Target Molecule</Label>
              <div className="grid grid-cols-1 gap-2">
                {END_MOLECULES.map((m) => (
                  <MoleculeCard
                    key={m.name}
                    molecule={m}
                    selected={endMol?.name === m.name}
                    onClick={() => setEndMol(m)}
                  />
                ))}
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3 pt-1">
              <Button type="button" variant="outline" onClick={() => navigate("/pathways")} className="flex-1">
                Cancel
              </Button>
              <Button type="submit" disabled={!canSubmit} className="flex-1 gap-2">
                <FlaskConical className="w-4 h-4" />
                Analyze & Create Pathway
              </Button>
            </div>

          </form>
        )}

      </div>
    </div>
  );
};

export default NewPathwayPage;
